// @/components/page-sections/productid-page/constReviews.js

export const constReviews = [
    {
      id: 1,
      rating: 5,
      comment: "Absolutely love this helmet!",
      date: "16/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet1",
    },
    {
      id: 2,
      rating: 4,
      comment: "Works well, pretty comfortable.",
      date: "15/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet2",
    },
    {
      id: 3,
      rating: 5,
      comment: "Quality exceeds expectations.",
      date: "14/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet3",
    },
    {
      id: 4,
      rating: 5,
      comment: "Super stylish and safe!",
      date: "14/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet4",
    },
    {
      id: 5,
      rating: 5,
      comment: "Nice good looking helmet.",
      date: "14/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet5",
    },
    {
      id: 6,
      rating: 3,
      comment: "It’s decent, but could be lighter.",
      date: "13/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet6",
    },
    {
      id: 7,
      rating: 4,
      comment: "Solid choice for the price.",
      date: "12/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet7",
    },
    {
      id: 8,
      rating: 5,
      comment: "Feels secure and snug!",
      date: "11/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet8",
    },
    {
      id: 9,
      rating: 4,
      comment: "Pretty good overall, recommended.",
      date: "10/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet9",
    },
    {
      id: 10,
      rating: 5,
      comment: "Better than my old helmet.",
      date: "09/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet10",
    },
    {
      id: 11,
      rating: 4,
      comment: "Met my expectations, would buy again.",
      date: "08/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet11",
    },
    {
      id: 12,
      rating: 5,
      comment: "Nice good looking helmet.",
      date: "07/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet12",
    },
    {
      id: 13,
      rating: 4,
      comment: "Comfortable and well-made.",
      date: "06/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet13",
    },
    {
      id: 14,
      rating: 5,
      comment: "Absolutely love this color!",
      date: "05/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet14",
    },
    {
      id: 15,
      rating: 4,
      comment: "No regrets. Solid buy.",
      date: "04/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet15",
    },
    {
      id: 16,
      rating: 2,
      comment: "Straps feel a bit flimsy.",
      date: "03/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet16",
    },
    {
      id: 17,
      rating: 5,
      comment: "Excellent protective gear.",
      date: "02/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet17",
    },
    {
      id: 18,
      rating: 4,
      comment: "Pretty decent quality.",
      date: "01/09/2025",
      image: "https://source.unsplash.com/random/300x300?helmet18",
    },
    {
      id: 19,
      rating: 5,
      comment: "Nice good looking helmet.",
      date: "31/08/2025",
      image: "https://source.unsplash.com/random/300x300?helmet19",
    },
    {
      id: 20,
      rating: 5,
      comment: "Top-tier. I’m very impressed!",
      date: "30/08/2025",
      image: "https://source.unsplash.com/random/300x300?helmet20",
    },
  ];
  